import Vue from 'vue'
import Vuex from 'vuex'

import * as getters from './getters'
import * as mutations from './mutations'

Vue.use(Vuex)

/**
 * Model Logic
 * - id is generated by the database, autoincrement
 * - key is generated by the system, 10 digit random number
 * - code must be unique
 * - notes must not be blank
 * Mutation Logic
 * - If id = 0, new entry, ensure code is unique
 * - If key is blank, view only, mutation not allowed
 * - Otherwise id and key must match for update to proceed, ensure code is unique
*/

const state = {
  // System generated
  id: 0,
  key: '',
  // User input
  code: '',
  notes: '',
  snackbarText: ''
}

export default new Vuex.Store({
  state,
  getters,
  mutations
})
