import Vuex from 'vuex'

import * as getters from './getters'
import makeMutations from './mutations'

/**
 * Model Logic
 * - id is generated by the database, autoincrement
 * - code must be unique, 3 to 30 characters
 * - notes must not be blank
 * Mutation Logic (might change)
 * - id = 0, new entry, ensure code is unique to be inserted into db (post)
 * - id > 0 and code exact match db, edit allowed, code must be unique (post)
 * - id > 0 and 2 character code matching last 2 in db, view mode, do not disclose code (get)
 * - id > 0 and code exact match db, edit mode (get)
*/

export default function makeStore (Vue, snackbar) {
  const state = {
    // Form states
    mode: 'edit',
    isLoading: false,
    // System generated
    id: 0,
    // User input
    code: '',
    notes: ''
  }

  Vue.use(Vuex)

  return new Vuex.Store({
    state,
    getters,
    mutations: makeMutations(snackbar)
  })
}
